export interface SurahMeta {
  number: number;
  arabic: string;
  english: string;
  translation: string;
  revelationType: "Meccan" | "Medinan";
  verses: number;
  juz: number; // juz where the surah starts
}

export const SURAH_LIST: SurahMeta[] = [
  { number: 1, arabic: "الفاتحة", english: "Al-Fatiha", translation: "The Opening", revelationType: "Meccan", verses: 7, juz: 1 },
  { number: 2, arabic: "البقرة", english: "Al-Baqara", translation: "The Cow", revelationType: "Medinan", verses: 286, juz: 1 },
  { number: 3, arabic: "آل عمران", english: "Ali 'Imran", translation: "Family of Imran", revelationType: "Medinan", verses: 200, juz: 3 },
  { number: 4, arabic: "النساء", english: "An-Nisa", translation: "The Women", revelationType: "Medinan", verses: 176, juz: 4 },
  { number: 5, arabic: "المائدة", english: "Al-Ma'ida", translation: "The Table Spread", revelationType: "Medinan", verses: 120, juz: 6 },
  { number: 6, arabic: "الأنعام", english: "Al-An'am", translation: "The Cattle", revelationType: "Meccan", verses: 165, juz: 7 },
  { number: 7, arabic: "الأعراف", english: "Al-A'raf", translation: "The Heights", revelationType: "Meccan", verses: 206, juz: 8 },
  { number: 8, arabic: "الأنفال", english: "Al-Anfal", translation: "The Spoils of War", revelationType: "Medinan", verses: 75, juz: 9 },
  { number: 9, arabic: "التوبة", english: "At-Tawba", translation: "The Repentance", revelationType: "Medinan", verses: 129, juz: 10 },
  { number: 10, arabic: "يونس", english: "Yunus", translation: "Jonah", revelationType: "Meccan", verses: 109, juz: 11 },
  { number: 11, arabic: "هود", english: "Hud", translation: "Hud", revelationType: "Meccan", verses: 123, juz: 11 },
  { number: 12, arabic: "يوسف", english: "Yusuf", translation: "Joseph", revelationType: "Meccan", verses: 111, juz: 12 },
  { number: 13, arabic: "الرعد", english: "Ar-Ra'd", translation: "The Thunder", revelationType: "Medinan", verses: 43, juz: 13 },
  { number: 14, arabic: "إبراهيم", english: "Ibrahim", translation: "Abraham", revelationType: "Meccan", verses: 52, juz: 13 },
  { number: 15, arabic: "الحجر", english: "Al-Hijr", translation: "The Rocky Tract", revelationType: "Meccan", verses: 99, juz: 14 },
  { number: 16, arabic: "النحل", english: "An-Nahl", translation: "The Bee", revelationType: "Meccan", verses: 128, juz: 14 },
  { number: 17, arabic: "الإسراء", english: "Al-Isra", translation: "The Night Journey", revelationType: "Meccan", verses: 111, juz: 15 },
  { number: 18, arabic: "الكهف", english: "Al-Kahf", translation: "The Cave", revelationType: "Meccan", verses: 110, juz: 15 },
  { number: 19, arabic: "مريم", english: "Maryam", translation: "Mary", revelationType: "Meccan", verses: 98, juz: 16 },
  { number: 20, arabic: "طه", english: "Ta-Ha", translation: "Ta-Ha", revelationType: "Meccan", verses: 135, juz: 16 },
  { number: 21, arabic: "الأنبياء", english: "Al-Anbiya", translation: "The Prophets", revelationType: "Meccan", verses: 112, juz: 17 },
  { number: 22, arabic: "الحج", english: "Al-Hajj", translation: "The Pilgrimage", revelationType: "Medinan", verses: 78, juz: 17 },
  { number: 23, arabic: "المؤمنون", english: "Al-Mu'minun", translation: "The Believers", revelationType: "Meccan", verses: 118, juz: 18 },
  { number: 24, arabic: "النور", english: "An-Nur", translation: "The Light", revelationType: "Medinan", verses: 64, juz: 18 },
  { number: 25, arabic: "الفرقان", english: "Al-Furqan", translation: "The Criterion", revelationType: "Meccan", verses: 77, juz: 18 },
  { number: 26, arabic: "الشعراء", english: "Ash-Shu'ara", translation: "The Poets", revelationType: "Meccan", verses: 227, juz: 19 },
  { number: 27, arabic: "النمل", english: "An-Naml", translation: "The Ant", revelationType: "Meccan", verses: 93, juz: 19 },
  { number: 28, arabic: "القصص", english: "Al-Qasas", translation: "The Stories", revelationType: "Meccan", verses: 88, juz: 20 },
  { number: 29, arabic: "العنكبوت", english: "Al-'Ankabut", translation: "The Spider", revelationType: "Meccan", verses: 69, juz: 20 },
  { number: 30, arabic: "الروم", english: "Ar-Rum", translation: "The Romans", revelationType: "Meccan", verses: 60, juz: 21 },
  { number: 31, arabic: "لقمان", english: "Luqman", translation: "Luqman", revelationType: "Meccan", verses: 34, juz: 21 },
  { number: 32, arabic: "السجدة", english: "As-Sajda", translation: "The Prostration", revelationType: "Meccan", verses: 30, juz: 21 },
  { number: 33, arabic: "الأحزاب", english: "Al-Ahzab", translation: "The Combined Forces", revelationType: "Medinan", verses: 73, juz: 21 },
  { number: 34, arabic: "سبأ", english: "Saba", translation: "Sheba", revelationType: "Meccan", verses: 54, juz: 22 },
  { number: 35, arabic: "فاطر", english: "Fatir", translation: "Originator", revelationType: "Meccan", verses: 45, juz: 22 },
  { number: 36, arabic: "يس", english: "Ya-Sin", translation: "Ya Sin", revelationType: "Meccan", verses: 83, juz: 22 },
  { number: 37, arabic: "الصافات", english: "As-Saffat", translation: "Those Who Set the Ranks", revelationType: "Meccan", verses: 182, juz: 23 },
  { number: 38, arabic: "ص", english: "Sad", translation: "The Letter Sad", revelationType: "Meccan", verses: 88, juz: 23 },
  { number: 39, arabic: "الزمر", english: "Az-Zumar", translation: "The Troops", revelationType: "Meccan", verses: 75, juz: 23 },
  { number: 40, arabic: "غافر", english: "Ghafir", translation: "The Forgiver", revelationType: "Meccan", verses: 85, juz: 24 },
  { number: 41, arabic: "فصلت", english: "Fussilat", translation: "Explained in Detail", revelationType: "Meccan", verses: 54, juz: 24 },
  { number: 42, arabic: "الشورى", english: "Ash-Shura", translation: "The Consultation", revelationType: "Meccan", verses: 53, juz: 25 },
  { number: 43, arabic: "الزخرف", english: "Az-Zukhruf", translation: "The Ornaments of Gold", revelationType: "Meccan", verses: 89, juz: 25 },
  { number: 44, arabic: "الدخان", english: "Ad-Dukhan", translation: "The Smoke", revelationType: "Meccan", verses: 59, juz: 25 },
  { number: 45, arabic: "الجاثية", english: "Al-Jathiya", translation: "The Crouching", revelationType: "Meccan", verses: 37, juz: 25 },
  { number: 46, arabic: "الأحقاف", english: "Al-Ahqaf", translation: "The Wind-Curved Sandhills", revelationType: "Meccan", verses: 35, juz: 26 },
  { number: 47, arabic: "محمد", english: "Muhammad", translation: "Muhammad", revelationType: "Medinan", verses: 38, juz: 26 },
  { number: 48, arabic: "الفتح", english: "Al-Fath", translation: "The Victory", revelationType: "Medinan", verses: 29, juz: 26 },
  { number: 49, arabic: "الحجرات", english: "Al-Hujurat", translation: "The Rooms", revelationType: "Medinan", verses: 18, juz: 26 },
  { number: 50, arabic: "ق", english: "Qaf", translation: "The Letter Qaf", revelationType: "Meccan", verses: 45, juz: 26 },
  { number: 51, arabic: "الذاريات", english: "Adh-Dhariyat", translation: "The Winnowing Winds", revelationType: "Meccan", verses: 60, juz: 26 },
  { number: 52, arabic: "الطور", english: "At-Tur", translation: "The Mount", revelationType: "Meccan", verses: 49, juz: 27 },
  { number: 53, arabic: "النجم", english: "An-Najm", translation: "The Star", revelationType: "Meccan", verses: 62, juz: 27 },
  { number: 54, arabic: "القمر", english: "Al-Qamar", translation: "The Moon", revelationType: "Meccan", verses: 55, juz: 27 },
  { number: 55, arabic: "الرحمن", english: "Ar-Rahman", translation: "The Beneficent", revelationType: "Medinan", verses: 78, juz: 27 },
  { number: 56, arabic: "الواقعة", english: "Al-Waqi'a", translation: "The Inevitable", revelationType: "Meccan", verses: 96, juz: 27 },
  { number: 57, arabic: "الحديد", english: "Al-Hadid", translation: "The Iron", revelationType: "Medinan", verses: 29, juz: 27 },
  { number: 58, arabic: "المجادلة", english: "Al-Mujadila", translation: "The Pleading Woman", revelationType: "Medinan", verses: 22, juz: 28 },
  { number: 59, arabic: "الحشر", english: "Al-Hashr", translation: "The Exile", revelationType: "Medinan", verses: 24, juz: 28 },
  { number: 60, arabic: "الممتحنة", english: "Al-Mumtahana", translation: "She That Is to Be Examined", revelationType: "Medinan", verses: 13, juz: 28 },
  { number: 61, arabic: "الصف", english: "As-Saf", translation: "The Ranks", revelationType: "Medinan", verses: 14, juz: 28 },
  { number: 62, arabic: "الجمعة", english: "Al-Jumu'a", translation: "The Congregation", revelationType: "Medinan", verses: 11, juz: 28 },
  { number: 63, arabic: "المنافقون", english: "Al-Munafiqun", translation: "The Hypocrites", revelationType: "Medinan", verses: 11, juz: 28 },
  { number: 64, arabic: "التغابن", english: "At-Taghabun", translation: "The Mutual Disillusion", revelationType: "Medinan", verses: 18, juz: 28 },
  { number: 65, arabic: "الطلاق", english: "At-Talaq", translation: "The Divorce", revelationType: "Medinan", verses: 12, juz: 28 },
  { number: 66, arabic: "التحريم", english: "At-Tahrim", translation: "The Prohibition", revelationType: "Medinan", verses: 12, juz: 28 },
  { number: 67, arabic: "الملك", english: "Al-Mulk", translation: "The Sovereignty", revelationType: "Meccan", verses: 30, juz: 29 },
  { number: 68, arabic: "القلم", english: "Al-Qalam", translation: "The Pen", revelationType: "Meccan", verses: 52, juz: 29 },
  { number: 69, arabic: "الحاقة", english: "Al-Haqqa", translation: "The Reality", revelationType: "Meccan", verses: 52, juz: 29 },
  { number: 70, arabic: "المعارج", english: "Al-Ma'arij", translation: "The Ascending Stairways", revelationType: "Meccan", verses: 44, juz: 29 },
  { number: 71, arabic: "نوح", english: "Nuh", translation: "Noah", revelationType: "Meccan", verses: 28, juz: 29 },
  { number: 72, arabic: "الجن", english: "Al-Jinn", translation: "The Jinn", revelationType: "Meccan", verses: 28, juz: 29 },
  { number: 73, arabic: "المزمل", english: "Al-Muzzammil", translation: "The Enshrouded One", revelationType: "Meccan", verses: 20, juz: 29 },
  { number: 74, arabic: "المدثر", english: "Al-Muddaththir", translation: "The Cloaked One", revelationType: "Meccan", verses: 56, juz: 29 },
  { number: 75, arabic: "القيامة", english: "Al-Qiyama", translation: "The Resurrection", revelationType: "Meccan", verses: 40, juz: 29 },
  { number: 76, arabic: "الإنسان", english: "Al-Insan", translation: "The Human", revelationType: "Medinan", verses: 31, juz: 29 },
  { number: 77, arabic: "المرسلات", english: "Al-Mursalat", translation: "The Emissaries", revelationType: "Meccan", verses: 50, juz: 29 },
  { number: 78, arabic: "النبأ", english: "An-Naba", translation: "The Tidings", revelationType: "Meccan", verses: 40, juz: 30 },
  { number: 79, arabic: "النازعات", english: "An-Nazi'at", translation: "Those Who Drag Forth", revelationType: "Meccan", verses: 46, juz: 30 },
  { number: 80, arabic: "عبس", english: "Abasa", translation: "He Frowned", revelationType: "Meccan", verses: 42, juz: 30 },
  { number: 81, arabic: "التكوير", english: "At-Takwir", translation: "The Overthrowing", revelationType: "Meccan", verses: 29, juz: 30 },
  { number: 82, arabic: "الانفطار", english: "Al-Infitar", translation: "The Cleaving", revelationType: "Meccan", verses: 19, juz: 30 },
  { number: 83, arabic: "المطففين", english: "Al-Mutaffifin", translation: "The Defrauding", revelationType: "Meccan", verses: 36, juz: 30 },
  { number: 84, arabic: "الانشقاق", english: "Al-Inshiqaq", translation: "The Sundering", revelationType: "Meccan", verses: 25, juz: 30 },
  { number: 85, arabic: "البروج", english: "Al-Buruj", translation: "The Mansions of the Stars", revelationType: "Meccan", verses: 22, juz: 30 },
  { number: 86, arabic: "الطارق", english: "At-Tariq", translation: "The Night-Comer", revelationType: "Meccan", verses: 17, juz: 30 },
  { number: 87, arabic: "الأعلى", english: "Al-A'la", translation: "The Most High", revelationType: "Meccan", verses: 19, juz: 30 },
  { number: 88, arabic: "الغاشية", english: "Al-Ghashiya", translation: "The Overwhelming", revelationType: "Meccan", verses: 26, juz: 30 },
  { number: 89, arabic: "الفجر", english: "Al-Fajr", translation: "The Dawn", revelationType: "Meccan", verses: 30, juz: 30 },
  { number: 90, arabic: "البلد", english: "Al-Balad", translation: "The City", revelationType: "Meccan", verses: 20, juz: 30 },
  { number: 91, arabic: "الشمس", english: "Ash-Shams", translation: "The Sun", revelationType: "Meccan", verses: 15, juz: 30 },
  { number: 92, arabic: "الليل", english: "Al-Layl", translation: "The Night", revelationType: "Meccan", verses: 21, juz: 30 },
  { number: 93, arabic: "الضحى", english: "Ad-Duha", translation: "The Morning Hours", revelationType: "Meccan", verses: 11, juz: 30 },
  { number: 94, arabic: "الشرح", english: "Ash-Sharh", translation: "The Relief", revelationType: "Meccan", verses: 8, juz: 30 },
  { number: 95, arabic: "التين", english: "At-Tin", translation: "The Fig", revelationType: "Meccan", verses: 8, juz: 30 },
  { number: 96, arabic: "العلق", english: "Al-'Alaq", translation: "The Clot", revelationType: "Meccan", verses: 19, juz: 30 },
  { number: 97, arabic: "القدر", english: "Al-Qadr", translation: "The Power", revelationType: "Meccan", verses: 5, juz: 30 },
  { number: 98, arabic: "البينة", english: "Al-Bayyina", translation: "The Clear Proof", revelationType: "Medinan", verses: 8, juz: 30 },
  { number: 99, arabic: "الزلزلة", english: "Az-Zalzala", translation: "The Earthquake", revelationType: "Medinan", verses: 8, juz: 30 },
  { number: 100, arabic: "العاديات", english: "Al-'Adiyat", translation: "The Courser", revelationType: "Meccan", verses: 11, juz: 30 },
  { number: 101, arabic: "القارعة", english: "Al-Qari'a", translation: "The Calamity", revelationType: "Meccan", verses: 11, juz: 30 },
  { number: 102, arabic: "التكاثر", english: "At-Takathur", translation: "The Rivalry in World Increase", revelationType: "Meccan", verses: 8, juz: 30 },
  { number: 103, arabic: "العصر", english: "Al-'Asr", translation: "The Declining Day", revelationType: "Meccan", verses: 3, juz: 30 },
  { number: 104, arabic: "الهمزة", english: "Al-Humaza", translation: "The Traducer", revelationType: "Meccan", verses: 9, juz: 30 },
  { number: 105, arabic: "الفيل", english: "Al-Fil", translation: "The Elephant", revelationType: "Meccan", verses: 5, juz: 30 },
  { number: 106, arabic: "قريش", english: "Quraysh", translation: "Quraysh", revelationType: "Meccan", verses: 4, juz: 30 },
  { number: 107, arabic: "الماعون", english: "Al-Ma'un", translation: "The Small Kindnesses", revelationType: "Meccan", verses: 7, juz: 30 },
  { number: 108, arabic: "الكوثر", english: "Al-Kawthar", translation: "The Abundance", revelationType: "Meccan", verses: 3, juz: 30 },
  { number: 109, arabic: "الكافرون", english: "Al-Kafirun", translation: "The Disbelievers", revelationType: "Meccan", verses: 6, juz: 30 },
  { number: 110, arabic: "النصر", english: "An-Nasr", translation: "The Divine Support", revelationType: "Medinan", verses: 3, juz: 30 },
  { number: 111, arabic: "المسد", english: "Al-Masad", translation: "The Palm Fiber", revelationType: "Meccan", verses: 5, juz: 30 },
  { number: 112, arabic: "الإخلاص", english: "Al-Ikhlas", translation: "The Sincerity", revelationType: "Meccan", verses: 4, juz: 30 },
  { number: 113, arabic: "الفلق", english: "Al-Falaq", translation: "The Daybreak", revelationType: "Meccan", verses: 5, juz: 30 },
  { number: 114, arabic: "الناس", english: "An-Nas", translation: "Mankind", revelationType: "Meccan", verses: 6, juz: 30 },
];
